# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# frozen_string_literal: true

default_platform(:android)

platform :android do


  desc 'Update version'
  lane :version do |options|
    updateVersion(options)
  end

  desc 'Submit a new Beta'
  lane :beta do |_options|
    gradle(task: 'clean bundleRelease')
    upload_to_play_store(
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_apk: true,
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

   desc "Fetches the latest version code from the Play Console and increments it by 1"
    lane :fetch_and_increment_build_number do
      app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

      version_codes = google_play_track_version_codes(
        package_name: app_identifier,
        track: "internal",
        json_key: ENV["ANDROID_JSON_KEY_FILE"]
      )

      updated_version_code = version_codes[0] + 1

      increment_version_code(
        version_code: updated_version_code
      )
    end

  lane :deploy do
      fetch_and_increment_build_number
      gradle(
        task: "bundle", # or "assemble", if you want to build an APK
        build_type: "release",
        properties: {
          "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
          "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
          "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
        }
      )

      upload_to_play_store(
        track: "internal",
        json_key: ENV["ANDROID_JSON_KEY_FILE"],
        skip_upload_metadata: true,
        skip_upload_screenshots: true,
        skip_upload_images: true,
        skip_upload_apk: true,
        track: 'internal',
      )
    end
  desc "Submit a new version to the internal track in the Google Play"
    lane :deploy_internal do
      gradle(task: "clean")
      gradle(
          task: 'bundle',
          build_type: 'Release'
      )
      upload_to_play_store(track: 'internal',aab: '../build/app/outputs/bundle/release/app-release.aab',)
    end

  desc 'Deploy a new version to the Google Play'
  lane :release do |_options|
    gradle(task: "clean assembleRelease")
    gradle(
        task: 'assemble',
        build_type: 'Release'
      )
      upload_to_play_store(
      package_name: 'com.regenki.regenki',
          track: 'production',
          rollout: '0.5',
          json_key:'fastlane/ivory-hallway-282008-8c8633bf9351.json',

        )
  end
end