# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# frozen_string_literal: true

default_platform(:android)

platform :android do


  desc 'Update version'
  lane :version do |options|
    updateVersion(options)
  end

  desc 'Submit a new Beta'
  lane :beta do |_options|
    gradle(task: 'clean bundleRelease')
    upload_to_play_store(
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_apk: true,
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

   desc 'Setup getLatest version code'
   private_lane :get_latest_version_code do

       internal_build_number = google_play_track_version_codes(
         track: "internal",
         package_name: ENV['BUNDLE_ID'],
         json_key: ENV["ANDROID_JSON_KEY_FILE"]
       )[0].to_i

       prod_build_number = google_play_track_version_codes(
         track: "production",
         package_name: ENV['BUNDLE_ID'],
         json_key: ENV["ANDROID_JSON_KEY_FILE"]
       )[0].to_i

       beta_build_number = google_play_track_version_codes(
         track: "beta",
         package_name: ENV['BUNDLE_ID'],
         json_key: ENV["ANDROID_JSON_KEY_FILE"]
       )[0].to_i

       alpha_build_number = google_play_track_version_codes(
         track: "alpha",

         package_name: ENV['BUNDLE_ID'],
         json_key: ENV["ANDROID_JSON_KEY_FILE"]
       )[0].to_i

       [internal_build_number, prod_build_number, beta_build_number, alpha_build_number].max
     end

  lane :deploy do
      get_latest_version_code
      gradle(
        task: "bundle", # or "assemble", if you want to build an APK
        build_type: "release",
        properties: {
          "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
          "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
          "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
        }
      )

      upload_to_play_store(
        track: "internal",
        json_key: ENV["ANDROID_JSON_KEY_FILE"],
        skip_upload_metadata: true,
        skip_upload_screenshots: true,
        skip_upload_images: true,
        skip_upload_apk: true,
        track: 'internal',
      )
    end
  desc "Submit a new version to the internal track in the Google Play"
    lane :deploy_internal do
      gradle(task: "clean")
      gradle(
          task: 'bundle',
          build_type: 'Release'
      )
      upload_to_play_store(track: 'internal',aab: '../build/app/outputs/bundle/release/app-release.aab',)
    end

  desc 'Deploy a new version to the Google Play'
  lane :release do |_options|
    gradle(task: "clean assembleRelease")
    gradle(
        task: 'assemble',
        build_type: 'Release'
      )
      upload_to_play_store(
      package_name: 'com.regenki.regenki',
          track: 'production',
          rollout: '0.5',
          json_key:'fastlane/ivory-hallway-282008-8c8633bf9351.json',

        )
  end
end