name: Deploy to Play Store
on:

  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "deploy_internal"
        type: choice
        options:
          - deploy_internal
          - promote_to_production
          - internal

# Declare default permissions as read-only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Setup up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Setup JAVA Environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'


      # Checkout the repository
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Setup Ruby, Bundler, and Gemfile dependencies.
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Setup up Flutter
        run: flutter pub get

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: regenki.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      # Configure Keystore.
      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/regenki.jks
          echo "storeFile=regenki.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          echo "$PLAY_STORE_CONFIG_JSON" | base64 --decode >> fastlane/ivory-hallway-282008-8c8633bf9351.json
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: ./android

      # Build and deploy with Fastlane.

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane ${{ github.event.inputs.lane || 'deploy_internal' }}
        env:
          FASTLANE_JSON_KEY_FILE: fastlane/ivory-hallway-282008-8c8633bf9351.json
        working-directory: ./android
