name: Deploy to Play Store
on:

  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "deploy_internal"
        type: choice
        options:
          - deploy_internal
          - promote_to_production
          - deploy

# Declare default permissions as read-only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Setup up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Setup JAVA Environment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: regenki_keystore
        with:
            fileName: "regenki.jks"
            encodedString: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: regenki_service_api
        with:
          fileName: "ivory-hallway-282008-8c8633bf9351.json"
          encodedString: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
      # Checkout the repository
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Setup Ruby, Bundler, and Gemfile dependencies.
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Setup up Flutter
        run: flutter pub get

      # Build and deploy with Fastlane.

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane env
          bundle exec fastlane ${{ github.event.inputs.lane || 'deploy' }}
        env:
          KEYSTORE_FILE: ${{steps.regenki_keystore.outputs.filepath}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
          KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
          KEY_ALIAS: ${{secrets.KEYSTORE_KEY_ALIAS}}
          ANDROID_JSON_KEY_FILE: ${{steps.regenki_service_api.outputs.filepath}}
          BUNDLE_ID: "com.regenki.regenki"
        working-directory: ./android